### ISSUE TITLE
Success -partial at least!!

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#11] opened 2015-06-11 14:07 UTC
![screen shot 2015-06-11 at 3 06 11 pm](https://cloud.githubusercontent.com/assets/12811998/8108929/8945f878-104b-11e5-9ea5-45f095ace76d.png)

**Comment by revajk** [comment] 2015-06-11 14:09
I think it should be tweaked to take the ID rather than the object will check. 

Reva.

**Comment by Anneli15** [comment] 2015-06-11 14:13
Ok, so how do I now add approval year and other info for this compound? I tried to select it and add but didn't seem to work? System added a year but didn't look like it was linked to the compound...

**Comment by Anneli15** [comment] 2015-06-11 14:18
All the spaces that show up as Object seem to have the info that I added but doesn't show unless you click on the i-circle. Would it be possible to have the added data shown as added (so "Discontinued" instead of StatusType object?

**Comment by mnowotka** [comment] 2015-06-11 15:34
Duplicate of https://github.com/chembl/IDG/issues/9.

**Closed as completed by mnowotka** 2015-06-11 15:34 UTC
