### ISSUE TITLE
Add mechanism tab

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#10] opened 2015-06-11 14:04 UTC
What is the space for "Moa qualifier" for?

**Comment by revajk** [comment] 2015-06-11 14:13
You can leave them blank.

**Comment by mnowotka** [comment] 2015-06-11 15:32
@revajk - still, it doesn't answer the question.

**Comment by mnowotka** [comment] 2015-06-11 15:35
@revajk - I've just noticed that this is a duplicate of https://github.com/chembl/IDG/issues/12, sorry!

**Closed as completed by mnowotka** 2015-06-11 15:35 UTC
